# Generated by Django 3.2 on 2023-02-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_image',
            field=models.ImageField(default='placeholder', upload_to='media/'),
        ),
    ]
