# Generated by Django 3.2 on 2023-02-14 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
